server:
  compression:
    enabled: ${SPRING_COMPRESSION_ENABLED:true}
logging:
  level:
    root: info
    gmky: info
    org.hibernate.orm.jdbc.bind: trace
spring:
  docker:
    compose:
      enabled: false
  application:
    name: ${SPRING_APPLICATION_NAME:CodeBase}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:gmky}
    password: ${SPRING_DATASOURCE_PASSWORD:Pu2vQz3jyfXB}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-curly-sky-90148409.ap-southeast-1.aws.neon.tech/test}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: db/changelog-master.xml
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ff748bf9b77b0e
    password: 82d4a4d96ea499
    properties:
      from: ${CB_EMAIL_FROM:admin@gmky.dev}
      name: ${CB_EMAIL_NAME:${spring.application.name}}
      signature: CodeBase Team
springdoc:
  api-docs:
    path: /api-docs
application:
  security:
    base64-secret: ${SPRING_SECURITY_BASE64_SECRET:Rm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uRm9yRGV2T25seURvTm90VXNlSW5Qcm9kdWN0aW9uCg==}
  aws:
    s3:
      bucket-name: gmky
      prefix: codebase