name: Verify application code
on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
  push:
    branches:
      - main
    paths:
      - "src/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set-up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Set-up Maven
        uses: actions/cache@v3
        with:
          path: "~/.m2"
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install dependencies
        run: mvn install
      - name: Run test
        run: mvn --batch-mode --update-snapshots verify